# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/superphenotype/.projects/Modular

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/superphenotype/.projects/Modular

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/superphenotype/.projects/Modular/CMakeFiles /home/superphenotype/.projects/Modular//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/superphenotype/.projects/Modular/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ModularLib

# Build rule for target.
ModularLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModularLib
.PHONY : ModularLib

# fast build rule for target.
ModularLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/build
.PHONY : ModularLib/fast

#=============================================================================
# Target rules for targets named Modular_Linux

# Build rule for target.
Modular_Linux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Modular_Linux
.PHONY : Modular_Linux

# fast build rule for target.
Modular_Linux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Modular_Linux.dir/build.make CMakeFiles/Modular_Linux.dir/build
.PHONY : Modular_Linux/fast

src/GameBanana.o: src/GameBanana.cpp.o
.PHONY : src/GameBanana.o

# target to build an object file
src/GameBanana.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/GameBanana.cpp.o
.PHONY : src/GameBanana.cpp.o

src/GameBanana.i: src/GameBanana.cpp.i
.PHONY : src/GameBanana.i

# target to preprocess a source file
src/GameBanana.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/GameBanana.cpp.i
.PHONY : src/GameBanana.cpp.i

src/GameBanana.s: src/GameBanana.cpp.s
.PHONY : src/GameBanana.s

# target to generate assembly for a file
src/GameBanana.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/GameBanana.cpp.s
.PHONY : src/GameBanana.cpp.s

src/NexusMods.o: src/NexusMods.cpp.o
.PHONY : src/NexusMods.o

# target to build an object file
src/NexusMods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/NexusMods.cpp.o
.PHONY : src/NexusMods.cpp.o

src/NexusMods.i: src/NexusMods.cpp.i
.PHONY : src/NexusMods.i

# target to preprocess a source file
src/NexusMods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/NexusMods.cpp.i
.PHONY : src/NexusMods.cpp.i

src/NexusMods.s: src/NexusMods.cpp.s
.PHONY : src/NexusMods.s

# target to generate assembly for a file
src/NexusMods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/NexusMods.cpp.s
.PHONY : src/NexusMods.cpp.s

src/Rename.o: src/Rename.cpp.o
.PHONY : src/Rename.o

# target to build an object file
src/Rename.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/Rename.cpp.o
.PHONY : src/Rename.cpp.o

src/Rename.i: src/Rename.cpp.i
.PHONY : src/Rename.i

# target to preprocess a source file
src/Rename.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/Rename.cpp.i
.PHONY : src/Rename.cpp.i

src/Rename.s: src/Rename.cpp.s
.PHONY : src/Rename.s

# target to generate assembly for a file
src/Rename.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/Rename.cpp.s
.PHONY : src/Rename.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Modular_Linux.dir/build.make CMakeFiles/Modular_Linux.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Modular_Linux.dir/build.make CMakeFiles/Modular_Linux.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ModularLib.dir/build.make CMakeFiles/ModularLib.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Modular_Linux.dir/build.make CMakeFiles/Modular_Linux.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ModularLib"
	@echo "... Modular_Linux"
	@echo "... src/GameBanana.o"
	@echo "... src/GameBanana.i"
	@echo "... src/GameBanana.s"
	@echo "... src/NexusMods.o"
	@echo "... src/NexusMods.i"
	@echo "... src/NexusMods.s"
	@echo "... src/Rename.o"
	@echo "... src/Rename.i"
	@echo "... src/Rename.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

